// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhi54NwLDCpZB4EZ355bI1OdgtSp4k8JY',
    appId: '1:683571646655:web:b8145ab8a13ec8a2ec360a',
    messagingSenderId: '683571646655',
    projectId: 'wecode-assignment',
    authDomain: 'wecode-assignment.firebaseapp.com',
    storageBucket: 'wecode-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA8xl9RvqwbOU1pOX2mYtl73ZnhKUb8dE',
    appId: '1:683571646655:android:5617e8d6f608e1c2ec360a',
    messagingSenderId: '683571646655',
    projectId: 'wecode-assignment',
    storageBucket: 'wecode-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-C601OW58fzeEwJZgstdQO5zoU49ciwQ',
    appId: '1:683571646655:ios:1bc8b1bc3f2d92d1ec360a',
    messagingSenderId: '683571646655',
    projectId: 'wecode-assignment',
    storageBucket: 'wecode-assignment.appspot.com',
    iosClientId: '683571646655-32cjlkme8uqn8gv94lncrji3261jnb7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.classAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-C601OW58fzeEwJZgstdQO5zoU49ciwQ',
    appId: '1:683571646655:ios:1bc8b1bc3f2d92d1ec360a',
    messagingSenderId: '683571646655',
    projectId: 'wecode-assignment',
    storageBucket: 'wecode-assignment.appspot.com',
    iosClientId: '683571646655-32cjlkme8uqn8gv94lncrji3261jnb7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.classAssignment',
  );
}
